gpu_id: [0,1,2,3]

exp_name: amodal3r/train_ss

model:
  ckpt_path: null
  type: ss

train_dataset:
    dataset_name: amodal3r
    data_root: ./dataset/abo_3dfuture_hssd
    split: train
    img_size: [512,512]

test_dataset:
    dataset_name: amodal3r
    data_root: ./dataset/abo_3dfuture_hssd
    split: test
    img_size: [512,512]

train:
    batch_size: 8
    lr: 1e-4
    beta1: 0.9
    beta2: 0.95
    weight_decay: 0.1
    warmup_iters: 1000
    n_epoch: 12
    limit_train_batches: 1.0
    limit_val_batches: 1.0
    check_val_every_n_epoch: 1
    use_rand_views: False
test:
    batch_size: 8

logger: 
    name: tensorboard
    dir: logs/${exp_name}